name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run Super-Linter
        uses: github/super-linter@main
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
