name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  update:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@main
   - name: Build the data and create local changes
     uses: actions/setup-python@v2
     with:
       python-version: '3.x'
       architecture: x64
   - name: Install requiremments
     run: |
       pip install -r requirements.txt
   - name: Process Data  
     run: |
       python Datopian.py
     env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
       